version: "3.7"
services:
  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "15672:15672" # RabbitMQ dashboard
      - "5672:5672" # RabbitMQ port
    environment:
      RABBITMQ_DEFAULT_USER: username
      RABBITMQ_DEFAULT_PASS: password
    networks:
      - rabbitmq-net

networks:
  rabbitmq-net:
    driver: bridge
# docker-compose up
# docker-compose down
