version: "3.7"
services:
  mysql:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: "database"
      MYSQL_USER: "mysql"
      MYSQL_PASSWORD: "mysql"
      MYSQL_ROOT_PASSWORD: "mysql"
    ports:
      - "3306:3306"
    volumes:
      - mysql_volume:/var/lib/mysql

volumes:
  mysql_volume:
# docker-compose up
# docker-compose down
