version: "3.7"
services:
  redis:
    image: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_volume:/bitnami/redis/data
volumes:
  redis_volume:
# docker-compose up
# docker-compose down
