version: "3.7"

services:
  mongodb:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root_user
      - MONGO_INITDB_ROOT_PASSWORD=root_password
      - MONGO_INITDB_DATABASE=admin
    restart: always
    volumes:
      - ./init-mongo.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - mongo_volume:/data/db
    ports:
      - 27017:27017

volumes:
  mongo_volume:
    driver: local
# docker-compose up --build --force-recreate
# docker-compose down
